language: python
python:
    - "2.6"
    - "2.7"
install:
    - pip install . --use-mirrors
    - pip install -r requirements.txt --use-mirrors
script: 
    - pylint --rcfile=.pylintrc -i y tbot
    - python setup.py test
notifications:
    irc:
    channels:
        - "irc.coldfront.net#welcometomars"
        - "chat.freenode.net#tbot"
    skip_join: true
